coolsite/config/routes.rb
Rails.application.routes.draw do

  #changing the landing page
  root 'static_pages#home'

  get 'static_pages/home'

  get 'static_pages/leaders'

  get 'static_pages/mission'

  get 'static_pages/photogal'

  get 'static_pages/commitment'
 
  get 'static_pages/new'

  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

coolsite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

coolsite/app/models/message.rb
class Message 
  include ActiveModel::Model
  attr_accessor :name, :email, :body
   validates :name, :email, :body, presence: true
end

coolsite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

coolsite/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def new
	 @message = Message.new
  	end

	  def create
    		@message = Message.new(message_params)

		respond_to do |format|
   		 if @message.valid?
    		  MessageMailer.contact_me(@message).deliver_now
    		  format.html{redirect_to new_message_url, notice: "Message received"}
   		 else
   		   format.html{render :new}
   		 end
		end
	end
  
def message_params
    params.require(:message).permit(:name, :email, :body)
  end
end

coolsite/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def leaders
  end

  def mission
  end

  def photogal
  end

  def commitment
  end
end

coolsite/app/helpers/application_helper.rb
module ApplicationHelper
end

coolsite/app/helpers/contacts_helper.rb
module ContactsHelper
end

coolsite/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

coolsite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>OSU BYX</title>
  <meta charset="utf-8" />
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- css -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Montserrat:400,700|Open+Sans:400,300,700,800", media: "screen" %>
  <!--Linking Bootstrap Style Sheet-->
	<%= stylesheet_link_tag 'bootstrap.min' %>
	<!--Linking Color Style Sheet-->
	<%= stylesheet_link_tag 'default' %>
	<%= stylesheet_link_tag 'font-awesome.min'%>

  <!-- =======================================================
    Theme Name: Alstar
    Theme URL: https://bootstrapmade.com/alstar-free-parallax-bootstrap-template/
    Author: BootstrapMade.com
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle nav</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <!-- Logo text or image -->
        <a class="navbar-brand" href="/static_pages/home">Ohio State BYX</a>

      </div>
      <div class="navigation collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <li> <%= link_to "Home", "/static_pages/home" %></li>
          <li><%= link_to "FAQ", "/static_pages/mission" %></li>
          <li> <%= link_to "Contact", "/contact-me" %></li>
        </ul>
      </div>
    </div>
  </nav>
<!-- intro area -->
  <div id="intro">
    <div class="intro-text">
      <div class="container">
        <div class="col-md-12">
          <div id="rotator">
            <h1><span class="1strotate">Ohio State, Beta Upsilon Chi</span></h1>
            <div class="line-spacer"></div>
            <p><span class="2ndrotate">Home of the Bucks, Building Men</span></p>
          </div>
        </div>
      </div>
    </div>
  </div>

    <%= yield %>
 <!-- Bottom widget -->
  <section id="bottom-widget" class="home-section bg-white">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="contact-widget wow bounceInLeft">
            <i class="fa fa-map-marker fa-4x"></i>
            <h5>Main Campus</h5>
            <p>
              109 Borough High Street,<br />London SE1 1NL
            </p>
          </div>
        </div>
        <div class="col-md-4">
          <div class="contact-widget wow bounceInUp">
            <i class="fa fa-phone fa-4x"></i>
            <h5>Call</h5>
            <p>
              +1 111 9998 7774<br> +1 245 4544 6855

            </p>
          </div>
        </div>
        <div class="col-md-4">
          <div class="contact-widget wow bounceInRight">
            <i class="fa fa-envelope fa-4x"></i>
            <h5>Email us</h5>
            <p>
              .com<br />
            </p>
          </div>
        </div>
      </div>
      <div class="row mar-top30">
        <div class="col-md-12">
          <h5>We're on social networks</h5>
          <ul class="social-network">
            <li><a href="#">
						<span class="fa-stack fa-2x">
							<i class="fa fa-circle fa-stack-2x"></i>
							<i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
						</span></a>
            </li>
            <li><a href="#">
						<span class="fa-stack fa-2x">
							<i class="fa fa-circle fa-stack-2x"></i>
							<i class="fa fa-dribbble fa-stack-1x fa-inverse"></i>
						</span></a>
            </li>
            <li><a href="#">
						<span class="fa-stack fa-2x">
							<i class="fa fa-circle fa-stack-2x"></i>
							<i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
						</span></a>
            </li>
            
          </ul>
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>Copyright &copy; Alstar. All rights reserved.</p>
          <div class="credits">
            <!--
              All the links in the footer should remain intact.
              You can delete the links only if you purchased the pro version.
              Licensing information: https://bootstrapmade.com/license/
              Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Alstar
            -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>



<%= javascript_include_tag "jquery" %>
<%= javascript_include_tag "jquery.nav" %>
<%= javascript_include_tag "bootstrap.min" %>
<%= javascript_include_tag "wow.min" %>

<%= javascript_include_tag "mb.bgndGallery" %>
<%= javascript_include_tag "mb.bgndGallery.effects" %>
<%= javascript_include_tag "jquery.simple-text-rotator.min" %>

<%= javascript_include_tag "jquery.scrollTo.min" %>
<%= javascript_include_tag "modernizr.custom" %>

<%= javascript_include_tag "stellar" %>
<%= javascript_include_tag "contactform" %>
<%= javascript_include_tag "custom" %>
  </body>
</html>

coolsite/app/views/messages/new.html.erb
<!-- Formating from Bootsnip-->
<%= notice %>
	<div class="bg-contact2" style="background-color: #ff0000;">
		<div class="container-contact2">
			<div class="wrap-contact2">
				<div class="contact2-form validate-form">
					<div class= "contact2-form-title">
					<label for "contact">
						Contact Us
					</label>
					<%= form_for @message, url: create_message_url do |f| %>
  							
 							 <%= @message.errors.full_messages.join(', ') %>

					<div class="wrap-input2 validate-input" data-validate="Name is required">
						<span class="focus-input2" data-placeholder="NAME" style ></span></br></br>
						<div class = "input2">
						 <%= f.text_field :name %>
						</div>
					
						

					</div>

					<div class="wrap-input2 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<span class="focus-input2" data-placeholder="EMAIL"></span></br></br>
						<div class = "input2">
						  <%= f.email_field :email, placeholder: 'email' %>
						</div>
						
					</div>

					<div class="wrap-input2 validate-input" data-validate = "Message is required">
						<div class = "input2">
						 <%= f.text_area :body, placeholder: 'body' %>
						</div>
						<span class="focus-input2" data-placeholder="MESSAGE"></span>
					</div>

					<div class="container-contact2-form-btn">
						<div class="wrap-contact2-form-btn">
							<div class="contact2-form-bgbtn"></div>
								 <%= f.submit "Send" %>
								 
						</div>
					</div>
				<% end %>
</div>
			</div>
		</div>
	</div>

coolsite/app/views/static_pages/_form.html.erb
<!--Generated by Aria on 4/14-->
<!--Edited by Aria on 4/15 to change header and styling of form fields-->

  <table class = "text-left">

	<tr>
   
        <h4 id ="prompt">Have a question? Send it to us!</h4>


    </tr>
</br>
    <tr>
      <td>
        <label for "name"> Name: </label>
      </td>
      <td>

        <%= form.text_field :name, id: :contact_name %>
      </td>
    </tr>
    <tr>
      <td>
        <label for "state"> Email: </label>
      </td>
      <td>
        <%= form.text_field :email, id: :contact_email%>
      </td>
    </tr>
    <tr>
      <td>
        <label for "country"> Subject: </label>
      </td>
      <td>
        <%= form.text_field subject, id: :contact_subject %>
      </td>
    </tr>
<tr>
      <td>
        <label for "country"> Message: </label>
      </td>
      <td>
        <%= form.text_field :message, id: :contact_message, :size=>"200" %>
      </td>
    </tr>
  </table>


    <div class="actions text-center">
      <%= form.submit "Send" %>
    </div>
  <% end %>

coolsite/app/views/static_pages/commitment.html.erb
<h1>StaticPages#commitment</h1>
<p>Find me in app/views/static_pages/commitment.html.erb</p>

coolsite/app/views/static_pages/home.html.erb
  

  <!-- About -->
  <section id="about" class="home-section bg-white">
    <div class="container">
      <div class="row">
        <div class="col-md-offset-2 col-md-8">
          <div class="section-heading">
            <h2>About us</h2>
            <div class="heading-line"></div>
            <h4>Also known as Brothers Under Christ, BYX exists for the purpose of establishing brotherhood and unity among college men based on the common bond of Jesus Christ.</h4>
          </div>
        </div>
      </div>
      <div class="row wow fadeInUp">
        <div class="col-md-6 about-img">
          <%= image_tag("about-img.jpg",  :alt =>"") %>
        </div>

        <div class="col-md-6 content">
          <h2>Our Brothers<h3>of Beta Upsilon Chi</h3> </h2>
          <p>
           Each of our members desire to grow in their relationship with Christ and their brothers. As they experience Christ-centered brotherhood and unity with other members, they learn to grow in their faith, develop lifelong friendships, and are equipped for post-graduate life. Members are expected to be committed to the different aspects of the fraternity including weekly chapter meetings, cell groups, social parties, as well philanthropic and service opportunities each semester.
          </p>
        </div>
      </div>
    </div>
  </section>

  <!-- Parallax 1 -->
  <section id="parallax1" class="home-section parallax">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="color-light">
            <h2 class="wow bounceInDown" data-wow-delay="0.5s">Behold how good and how pleasant it is for brothers to dwell together in unity!</h2>
            <p class="lead wow bounceInUp" data-wow-delay="1s">Psalm 133:1</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Our Movement -->
  <section id="services" class="home-section bg-white">
    <div class="container">
      <div class="row">
        <div class="col-md-offset-2 col-md-8">
          <div class="section-heading">
            <h2>Our Movement</h2>
            <div class="heading-line"></div>
            <p>We are joining a movement to live as Christ has called us.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div id="carousel-service" class="service carousel slide">

            <!-- slides -->
            <div class="carousel-inner">
              <div class="item active">
                <div class="row">
                  <div class="col-sm-12 col-md-offset-1 col-md-6">
                    <div class="wow bounceInLeft">
                      <h4>Chapter Meetings</h4>
                      <p>Each week the entire chapter gathers for prayer, worship, a short encouragement and challenge from the Bible, and announcements. Chapter meetings are central to developing brotherhood and unity in the fraternity.</p>
                    </div>
                  </div>
                  <div class="col-sm-12 col-md-5">
                    <div class="screenshot wow bounceInRight">
                      <%= image_tag("screenshots/1.jpg",  :class=>"img-responsive",  :alt =>"") %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="row">
                  <div class="col-sm-12 col-md-offset-1 col-md-6">
                    <div class="wow bounceInLeft">
                      <h4>Cell Groups</h4>
                      <p>Cell groups are smaller, Christ-centered communities ranging from 4-6 men who are devoted to keeping each other in an active, personal relationship with Christ.</p>
                    </div>
                  </div>
                  <div class="col-sm-12 col-md-5">
                    <div class="screenshot wow bounceInRight">
                      <%= image_tag("screenshots/2.jpg",  :class =>"img-responsive",  :alt =>"") %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="row">
                  <div class="col-sm-12 col-md-offset-1 col-md-6">
                    <div class="wow bounceInLeft">
                      <h4>Parties</h4>
                      <p>Our parties are intended to promote an exciting, entertaining environment for all to attend without compromising any of our stated values. They range from formals, themed date parties, open parties, mixers, tailgates and date dashes. They are entirely free of alcohol. BYX is also involved in events with other fraternities and sororities, including mixers, philanthropies, service opportunities and campus-wide events.</p>
                    </div>
                  </div>
                  <div class="col-sm-12 col-md-5">
                    <div class="screenshot wow bounceInRight">
                      <%= image_tag("screenshots/3.jpg", :class=>"img-responsive",  :alt =>"") %>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Indicators -->
            <ol class ="carousel-indicators">
              <li data-target="#carousel-service" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-service" data-slide-to="1"></li>
              <li data-target="#carousel-service" data-slide-to="2"></li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Other Resources -->
  <section id="portfolio" class="home-section bg-gray">
    <div class="container">
      <div class="row">
        <div class="col-md-offset-2 col-md-8">
          <div class="section-heading">
            <h2>Other Resources</h2>
            <div class="heading-line"></div>
            <p>Find out more about other involvements and activities happening.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">

          <ul id="og-grid" class="og-grid">
            <li>
              <a href="#">
								<%= image_tag("works/1.jpg",  :alt =>"", :style=> "max-width: 80%") %>
							</a>
            </li>
            <li>
              <a href="#" >
								<%= image_tag("works/2.jpg",  :alt =>"", :style=> "max-width: 80%") %>
							</a>
            </li>
            <li>
              <a href="#" data-title="Portfolio title" data-description="basketball">
								<%= image_tag("works/3.jpg",  :alt =>"img01", :style=> "max-width: 80%") %>
							</a>
            </li>
            <li>
              <a href="#"  data-title="Portfolio title" data-description="not in yet">
								<%= image_tag("works/4.jpg",  :alt =>"img01", :style=> "max-width: 80%") %>
							</a>
            </li>
            <li>
              <a href="#"  data-title="Portfolio title" data-description="boys">
								<%= image_tag("works/5.jpg",  :alt =>"img01", :style=> "max-width: 80%") %>
							</a>
            </li>
            <li>
              <a href="#"  data-title="boys.">
								<%= image_tag("works/6.jpg",  :alt =>"img01", :style=> "max-width: 80%") %>
							</a>
            </li>
            <li>
              <a href="#"  data-title="Portfolio title" data-description="not in yet.">
								<%= image_tag("works/7.jpg",  :alt =>"img01", :style=> "max-width: 80%") %>
							</a>
            </li>
            <li>
              <a href="#"  data-title="Portfolio title" data-description="boys">
								<%= image_tag("works/8.jpg",  :alt =>"img01", :style=> "max-width: 80%") %>
							</a>
            </li>
            <li>
              <a href="#"  data-title="Portfolio title" data-description="not in yet">
								<%= image_tag("works/9.jpg",  :alt =>"img01", :style=> "max-width: 80%") %>
							</a>
            </li>
		  <li>
              <a href="#"  data-title="Portfolio title" data-description="not in yet.">
								<%= image_tag("works/10.jpg",  :alt =>"img01", :style=> "max-width: 80%") %>
							</a>
            </li>
            <li>
              <a href="#" data-title="Portfolio title" data-description="boys">
								<%= image_tag("works/11.jpg",  :alt =>"img01", :style=> "max-width: 80%") %>
							</a>
            </li>
            <li>
              <a href="#"  data-title="Portfolio title" data-description="not in yet">
								<%= image_tag("works/1.jpg",  :alt =>"img01", :style=> "max-width: 80%") %>
							</a>
            </li>
          </ul>

        </div>
      </div>
    </div>
  </section>

  <!-- Parallax 2 -->
  <section id="parallax2" class="home-section parallax" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="clients">
            <li class="wow fadeInDown" data-wow-delay="0.3s"><a href="#" class = "bau">Brotherhood and Unity</a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <!-- Team -->
  <section id="team" class="home-section bg-white">
    <div class="container">
      <div class="row">
        <div class="col-md-offset-2 col-md-8">
          <div class="section-heading">
            <h2>Our Leadership</h2>
            <div class="heading-line"></div>
            <p>All current OSU students with a passion for investing in others</p>
          </div>
        </div>
      </div>
      <div class="row">
	<div class="col-xs-0 col-sm-1 col-md-1 col-lg-1"></div>
        <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
          <div class="box-team wow bounceInUp" data-wow-delay="0.1s">
            <%= image_tag("team/1.jpg",  :alt =>"", :class =>"img-circle img-responsive", :style => "min-width: 65%;") %>
            <h4>Trent Marean</h4>
            <p>Vice President</p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2" data-wow-delay="0.3s">
          <div class="box-team wow bounceInUp">
            <%= image_tag("team/2.jpg",  :alt =>"",  :class =>"img-circle img-responsive", :style => "max-width: 95%;") %>
            <h4>Griffin Rea</h4>
            <p>President</p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2" data-wow-delay="0.5s">
          <div class="box-team wow bounceInUp">
            <%= image_tag("team/3.jpg",  :alt =>"",  :class =>"img-circle img-responsive", :style => "min-width: 70%;") %>
            <h4>Grant Newberry</h4>
            <p>Pledge Captain</p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2" data-wow-delay="0.7s">
          <div class="box-team wow bounceInUp">
            <%= image_tag("team/4.jpg",  :alt =>"",  :class =>"img-circle img-responsive", :style => "max-width: 95%;") %>
            <h4>Sam Myer</h4>
            <p>Pledge Trainer</p>
          </div>
        </div>
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2" data-wow-delay="0.7s">
          <div class="box-team wow bounceInUp">
            <%= image_tag("team/5.jpg",  :alt =>"",  :class =>"img-circle img-responsive", :style => "max-width: 95%;") %>
            <h4>Ben Parillo</h4>
            <p>Treasurer</p>
          </div>
        </div>
      </div>
    </div>
  </section>


 

coolsite/app/views/static_pages/leaders.html.erb
 <div class="row">
        <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project One</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Two</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit aliquam aperiam nulla perferendis dolor nobis numquam, rem expedita, aliquid optio, alias illum eaque. Non magni, voluptates quae, necessitatibus unde temporibus.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Three</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Four</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit aliquam aperiam nulla perferendis dolor nobis numquam, rem expedita, aliquid optio, alias illum eaque. Non magni, voluptates quae, necessitatibus unde temporibus.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Five</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Six</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit aliquam aperiam nulla perferendis dolor nobis numquam, rem expedita, aliquid optio, alias illum eaque. Non magni, voluptates quae, necessitatibus unde temporibus.</p>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->

      <!-- Pagination -->
      <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>

    </div>
    <!-- /.container -->

   

coolsite/app/views/static_pages/mission.html.erb
 <section id="question1" class="home-section parallax">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="color-light">
            <h2 class="wow bounceInDown" data-wow-delay="0.5s">Is BYX trying to be the church?</h2>
            <p class="lead wow bounceInUp" data-wow-delay="1s">Brothers Under Christ is a fraternity of college men coming together under the common bond of Jesus Christ. We are not the church, nor do we aspire to be. We strongly encourage our members to be a part of a local congregation, growing along with the body of Christ. While we do strive to develop brotherhood and unity among Christian college men, we should in no way be considered a substitute for the Bride of Christ. BYX is a Christian social fraternity were men of faith can gather to challenge each other spiritually in brotherhood and impact the campus socially. BYX Purdue members are involved in, not just attendees of, a multitude of Lafayette/West Lafayette churches.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

 <section id="question2" class="home-section parallax">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="color-light">
            <h2 class="wow bounceInDown" data-wow-delay="0.5s">What about alcohol?</h2>
            <p class="lead wow bounceInUp" data-wow-delay="1s">We do not allow alcohol at any BYX-sponsored events or parties. Though we do not regard the consumption of alcohol in and of itself as sin, we do require our members to abstain from drinking alcohol in Tippecanoe county as an active member. We do this for two reasons: first, to promote unity among our members that are both younger and older than 21 years of age. Secondly, we as Christians are called biblically to be above reproach and this is one way that we have chosen to do that during our time in college.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

 <section id="question3" class="home-section parallax">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="color-light">
            <h2 class="wow bounceInDown" data-wow-delay="0.5s">What about hazing?</h2>
            <p class="lead wow bounceInUp" data-wow-delay="1s">The purpose of BYX is to promote unity and brotherhood within the fraternity based on the common bond of Jesus Christ. This is accomplished without emotional or physical punishment, abuse, or humiliation. Our members are constantly striving to live a Christian witness, promoting the name of Jesus through service to both member and new members or those pledging the fraternity.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

 <section id="question4" class="home-section parallax">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="color-light">
            <h2 class="wow bounceInDown" data-wow-delay="0.5s">Cost?</h2>
            <p class="lead wow bounceInUp" data-wow-delay="1s">The cost of living at BYX – Fairway is a fraction of the cost of other fraternities/sororities because of our cooperative living arrangements. Since we have no cleaning staff or chefs, costs are reduced dramatically. Cost specifics are provided at all rush events or can be obtained upon request. Please feel free contact our chapter for cost-related or any other questions you may have!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

coolsite/app/views/static_pages/new.html.erb
<%= form_for @message, url: create_message_url do |f| %>
  <%= notice %>
  <%= @message.errors.full_messages.join(', ') %>

  <%= f.text_field :name, placeholder: 'name' %>
  <%= f.email_field :email, placeholder: 'email' %>
  <%= f.text_area :body, placeholder: 'body' %>
  <%= f.submit 'Send' %>
<% end %>

coolsite/app/views/static_pages/photogal.html.erb
<h1>StaticPages#photogal</h1>
<p>Find me in app/views/static_pages/photogal.html.erb</p>